from pymongo import MongoClient
import os

# Ambil URI dan info database dari environment variable (atau fallback default)
MONGO_URI = os.getenv("MONGO_URI", "mongodb+srv://ahmadihdafalah:amdryzen1010@cluster0.10a3ead.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
DB_NAME = os.getenv("DB_NAME", "girlfriend_app")
COLLECTION_NAME = os.getenv("COLLECTION_NAME", "user_entries")

client = MongoClient(MONGO_URI)
db = client[DB_NAME]
collection = db[COLLECTION_NAME]

def save_user_data(name, dob, jadian):
    data = {
        "name": name,
        "dob": dob.isoformat(),
        "jadian": jadian.isoformat()
    }
    collection.insert_one(data)
